### ISSUE TITLE
List of dependencies

### ISSUE THREAD

**Issue by suhanacharya** [akshayrb22/Conquest_IITKGP_2017#2]
Its a bit confusing to use the repository as a reference, due to lack of **list of dependencies** *used* in the python environment :confused:. Could you add a *.yml* file or a *.txt* file with all the dependency.

**Comment by akshayrb22** [comment]
Sorry for the delay. I'll work on it and push it to the master branch.

**Comment by akshayrb22** [comment]
List of dependencies added.
